import_from_git(
  url: "https://github.com/Qase/BuildingTemplates-iOS.git", # The URL of the repository to import the Fastfile from.
  branch: "setup-swiftgen", # The branch to checkout on the repository
  path: "fastlane/Fastfile_Base", # The path of the Fastfile in the repository
)